drop table if exists users;

create table users (
                        id bigint generated by default as identity,
                        username varchar(255),
                        password varchar(255),
                        roles varchar(255),
                        primary key (id)
);

insert into users (username, password, roles) values ('liam@naver.com','$2a$10$nDVHMpuR8W6MxPW9aDn4X.E5sAFBr5672MkezaVkGgjwI5RqpKUae','ROLE_USER');
insert into users (username, password, roles) values ('asdsd@naver.com','$2a$10$nDVHMpuR8W6MxPW9aDn4X.E5sAFBr5672MkezaVkGgjwI5RqpKUae','ADMIN');