server:
  port: 8081

spring:
  cloud:
    gateway:
      routes:
        - id: user
          uri: http://localhost:8082
          predicates:
            - Path=/user/**
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/test
    username: postgres
    password: 11223344
  jwt:
    secret: sdjfghadsfuiyiffkbasdkfnasdkjfhasdfkjhsadfjkh
    token:
      access-expiration-time: 9000000
      refresh-expiration-time: 604800000

  data:
    redis:
      host: localhost
      port: 6379

  sql:
    init:
      data-locations: classpath:data/data.sql